//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProceduralFamilyTree.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProceduralFamilyTree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mary
        ///Elizabeth
        ///Sarah
        ///Margaret
        ///Susan
        ///Anna
        ///Martha
        ///Emma
        ///Frances
        ///Catherine
        ///Jane
        ///Helen
        ///Emily
        ///Darcy
        ///Lucy
        ///Alice
        ///Rebecca
        ///Caroline
        ///Eliza
        ///Julia
        ///Louisa
        ///Maria
        ///Harriet
        ///Ellen
        ///Laura
        ///Sophia
        ///Nancy
        ///Amelia
        ///Charlotte
        ///Henrietta
        ///Isabella
        ///Lillian
        ///Matilda
        ///Adeline
        ///Louise
        ///Clara
        ///Eleanor
        ///Florence
        ///Mabel
        ///Ada
        ///Agnes
        ///Ida
        ///Rose
        ///Marie
        ///Esther
        ///Ethel
        ///Grace
        ///Eva
        ///Victoria
        ///Lydia
        ///Ruth.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John
        ///William
        ///James
        ///George
        ///Charles
        ///Joseph
        ///Henry
        ///Thomas
        ///Edward
        ///Robert
        ///Samuel
        ///Benjamin
        ///Frank
        ///David
        ///Brian
        ///Bryan
        ///Xander
        ///Andrew
        ///Peter
        ///Daniel
        ///Frederick
        ///Albert
        ///Richard
        ///Arthur
        ///Alexander
        ///Walter
        ///Edwin
        ///Lewis
        ///Oscar
        ///Michael
        ///Matthew
        ///Patrick
        ///Abraham
        ///Martin
        ///Theodore
        ///Nathaniel
        ///Jonathan
        ///Stephen
        ///Anthony
        ///Jeremiah
        ///Eugene
        ///Isaac
        ///Lawrence
        ///Caleb
        ///Joshua
        ///Clarence
        ///Philip
        ///Herman
        ///Augustus
        ///Horace
        ///Levi
        ///Simon
        ///Elias
        ///James
        ///William
        ///John
        ///David
        ///Robert
        ///Michael
        ///Thomas
        ///Andrew
        ///Richard
        ///Dan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalewski
        ///Thielke
        ///DeBroux
        ///Moran
        ///Müller
        ///Schmidt
        ///Schneider
        ///Fischer
        ///Weber
        ///Meyer
        ///Wagner
        ///Becker
        ///Schulz
        ///Hoffmann
        ///Schäfer
        ///Koch
        ///Bauer
        ///Richter
        ///Klein
        ///Wolf
        ///Schwarz
        ///Neumann
        ///Schmitz
        ///Zimmermann
        ///Braun
        ///Krüger
        ///Hofmann
        ///Hartmann
        ///Lange
        ///Schmid
        ///Schreiber
        ///Weiß
        ///Werner
        ///Krause
        ///Maier
        ///Lehmann
        ///Schulte
        ///Schuhmann
        ///Mayer
        ///Huber
        ///Kühn
        ///Frank
        ///Kaiser
        ///Hahn
        ///Jäger
        ///Peters
        ///Lang
        ///Vogel
        ///Keller
        ///Hermann
        ///Thomas
        ///Scholz
        ///Stein
        ///Ludwig
        ///Nowak
        ///Kowalski
        ///Wiśniewski
        ///Wójcik
        ///Kowalczyk
        ///Kamiński
        ///Lewandowski
        ///Zie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
    }
}
